### ISSUE TITLE
XamlParseException on newest update

### ISSUE THREAD

**Issue by ghost** [TheRealVira/FileSearch#2]
Everything worked fine until the new update was released. Now i get a XamlParseException on the application startup. Additional information:
Exception thrown: 'System.Windows.Markup.XamlParseException' in PresentationFramework.dll

Additional information: 'The invocation of the constructor on type 'FileSearch.SearchFile' that matches the specified binding constraints threw an exception.' Line number '22' and line position '18'.

**Comment by TheRealVira** [comment]
I think it's fixed now. The problem was, that the designer initialized the usercontrol (and triggers the constructor), which then wants to load the plugins which brings it to collapse. I fixed it through:

`if (!(Application.Current is App))
             {
                 return;
             }`

Shout out to ["Patrick" and "weston"](http://stackoverflow.com/a/19979195)!
